on: [push]

jobs:
  upload-file:
    runs-on: ubuntu-latest
    name: Upload test report to CS
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Upload E2E Report
        id: upload
        uses: Jayesh2812/upload-to-cs@v1.6
        with:
          file_path: test-report/index.html
          management_token: ${{ secrets.MANAGEMENT_TOKEN }}
          api_key: blt858e12437ac2679e
          folder_uid: blt7e065426f910165e

      - name: Link for E2E Report
        run: echo "Link for E2E Report - ${{ steps.upload.outputs.link }}" >> $GITHUB_STEP_SUMMARY
