on: [push]

jobs:
  upload-file:
    runs-on: ubuntu-latest
    name: Upload test report to CS
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Upload
        id: upload
        uses: Jayesh2812/upload-report-to-cs@v1.8
        with: 
          path: test-report/
          management_token: ${{ secrets.MANAGEMENT_TOKEN }}
          api_key: blt858e12437ac2679e
          parent_uid: blt7e065426f910165e


      - name: Link for Report
        run: echo "${{ steps.upload.outputs.link }}"
      